[package]
name = "test-pyo3"
version = "0.1.0"
authors = ["Christian Espinoza <chespinoza@gmail.com>"]
edition = "2018"

[lib]
name = "string_sum"
crate-type =["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.5.3"
features = ["extension-module"]
